language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed trangnd/udagram-api-feed:v1
  - docker tag udagram-api-user trangnd/udagram-api-user:v1
  - docker tag udagram-frontend trangnd/udagram-frontend:v1
  - docker tag reverseproxy trangnd/reverseproxy:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trangnd/udagram-api-feed:v1
  - docker push trangnd/udagram-api-user:v1
  - docker push trangnd/udagram-frontend:v1
  - docker push trangnd/reverseproxy:v1
